architecture:
  input_dim: 52
  hidden_dim:
  output_dim: 13

learning_rate: 0.001

mapper:
  1: 'benign'
  2: 'bot'
  3: 'brute force -web'
  4: 'brute force -xss'
  5: 'ddos attack-hoic'
  6: 'dos attacks-goldeneye'
  7: 'dos attacks-hulk'
  8: 'dos attacks-slowhttptest'
  9: 'dos attacks-slowloris'
  10: 'ftp-bruteforce'
  11: 'infilteration'
  12: 'sql injection'
  13: 'ssh-bruteforce'

attributes: [
  'protocol',
  'totlen_fwd_pkts',
  'fwd_pkt_len_max',
  'fwd_pkt_len_mean',
  'bwd_pkt_len_min',
  'bwd_pkt_len_mean',
  'bwd_pkt_len_std',
  'flow_byts_s',
  'flow_iat_std',
  'fwd_iat_tot',
  'fwd_iat_mean',
  'fwd_iat_std',
  'bwd_iat_tot',
  'bwd_iat_std',
  'bwd_iat_max',
  'bwd_iat_min',
  'fwd_psh_flags',
  'bwd_psh_flags',
  'fwd_urg_flags',
  'bwd_urg_flags',
  'fwd_pkts_s',
  'bwd_pkts_s',
  'pkt_len_min',
  'pkt_len_mean',
  'pkt_len_std',
  'fin_flag_cnt',
  'syn_flag_cnt',
  'rst_flag_cnt',
  'psh_flag_cnt',
  'ack_flag_cnt',
  'urg_flag_cnt',
  'cwe_flag_count',
  'ece_flag_cnt',
  'down_up_ratio',
  'fwd_seg_size_avg',
  'bwd_seg_size_avg',
  'fwd_byts_b_avg',
  'fwd_pkts_b_avg',
  'fwd_blk_rate_avg',
  'bwd_byts_b_avg',
  'bwd_pkts_b_avg',
  'bwd_blk_rate_avg',
  'subflow_fwd_byts',
  'subflow_bwd_pkts',
  'init_fwd_win_byts',
  'init_bwd_win_byts',
  'fwd_seg_size_min',
  'active_std',
  'active_max',
  'active_min',
  'idle_std',
  'idle_max'
 ]
